# fly.toml app configuration file generated for eigentask-api on 2025-09-03T21:39:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eigentask-api'
primary_region = 'lhr'

[build]

[deploy]
  release_command = "python -m alembic -c alembic.ini upgrade head"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.healthz]
    port = 8080
    type = "http"
    interval = "15s"
    timeout = "2s"
    path = "/healthz"
